#!/bin/bash
set -euo pipefail

TYPE=debug

if [ "$TYPE" == "debug" ]; then
  cargo build
else
  cargo build --release
fi

/opt/devkitpro/devkitPPC/bin/powerpc-eabi-strip -g -o wut-rust-demo.strip.elf "target/powerpc-unknown-eabi/$TYPE/wut-rust-demo"
elf2rpl wut-rust-demo.strip.elf wut-rust-demo.rpx
